// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnTheTaps.Shared.Models;

#nullable disable

namespace OnTheTaps.Shared.Migrations
{
    [DbContext(typeof(BigBeerDataCoreContext))]
    [Migration("20221121215633_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnTheTaps.Shared.Models.Beer", b =>
                {
                    b.Property<int>("Bid")
                        .HasColumnType("int");

                    b.Property<double>("Abv")
                        .HasColumnType("float")
                        .HasColumnName("ABV");

                    b.Property<string>("BaseStyle")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("(case when charindex(' - ',[Style])=(0) then [Style] else rtrim(left([Style],charindex(' - ',[Style]))) end)", false);

                    b.Property<string>("BeerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeerPic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrewerId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SLUG");

                    b.Property<string>("Style")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Bid");

                    b.HasIndex(new[] { "BrewerId" }, "IX_Beers_BrewerId");

                    b.ToTable("Beers");
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.BeerColour", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Hex")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BeerColour", (string)null);
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.BeerFamily", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("BeerTypeId")
                        .HasColumnType("int")
                        .HasColumnName("BeerTypeID");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BeerTypeId" }, "IX_BeerFamily_BeerTypeID");

                    b.ToTable("BeerFamily", (string)null);
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.BeerStyle", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<double>("Abvhigh")
                        .HasColumnType("float")
                        .HasColumnName("ABVHigh");

                    b.Property<double>("Abvlow")
                        .HasColumnType("float")
                        .HasColumnName("ABVLow");

                    b.Property<int>("FamilyId")
                        .HasColumnType("int")
                        .HasColumnName("FamilyID");

                    b.Property<double>("FinalGravHigh")
                        .HasColumnType("float");

                    b.Property<double>("FinalGravLow")
                        .HasColumnType("float");

                    b.Property<double>("Ibuhigh")
                        .HasColumnType("float")
                        .HasColumnName("IBUHigh");

                    b.Property<double>("Ibulow")
                        .HasColumnType("float")
                        .HasColumnName("IBULow");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrigGravHigh")
                        .HasColumnType("float");

                    b.Property<double>("OrigGravLow")
                        .HasColumnType("float");

                    b.Property<int>("SrmhighId")
                        .HasColumnType("int")
                        .HasColumnName("SRMHighID");

                    b.Property<int>("SrmlowId")
                        .HasColumnType("int")
                        .HasColumnName("SRMLowID");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    b.Property<int>("YeastId")
                        .HasColumnType("int")
                        .HasColumnName("YeastID");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FamilyId" }, "IX_BeerStyle_FamilyID");

                    b.HasIndex(new[] { "SrmhighId" }, "IX_BeerStyle_SRMHighID");

                    b.HasIndex(new[] { "SrmlowId" }, "IX_BeerStyle_SRMLowID");

                    b.HasIndex(new[] { "TypeId" }, "IX_BeerStyle_TypeID");

                    b.HasIndex(new[] { "YeastId" }, "IX_BeerStyle_YeastID");

                    b.ToTable("BeerStyle", (string)null);
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.BeerType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BeerType", (string)null);
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.BeerYeast", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("BaseColour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BeerYeast", (string)null);
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.Brewer", b =>
                {
                    b.Property<int>("BrewerId")
                        .HasColumnType("int");

                    b.Property<string>("BrewerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SLUG");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("URL");

                    b.HasKey("BrewerId");

                    b.ToTable("Brewers");
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.Checkin", b =>
                {
                    b.Property<double>("CheckinId")
                        .HasColumnType("float");

                    b.Property<int>("Bid")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckinTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("int");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.HasKey("CheckinId");

                    b.HasIndex(new[] { "Bid" }, "IX_Checkins_Bid");

                    b.HasIndex(new[] { "EstablishmentId" }, "IX_Checkins_EstablishmentId");

                    b.ToTable("Checkins");
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.Establishment", b =>
                {
                    b.Property<int>("EstablishmentId")
                        .HasColumnType("int");

                    b.Property<int>("BaseZoom")
                        .HasColumnType("int");

                    b.Property<string>("EstablishmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastCheckinUpdate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<bool>("MaxedCheckinHistory")
                        .HasColumnType("bit");

                    b.HasKey("EstablishmentId");

                    b.HasIndex(new[] { "LocationId" }, "IX_Establishments_LocationId");

                    b.ToTable("Establishments");
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.Beer", b =>
                {
                    b.HasOne("OnTheTaps.Shared.Models.Brewer", "Brewer")
                        .WithMany("Beers")
                        .HasForeignKey("BrewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brewer");
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.BeerFamily", b =>
                {
                    b.HasOne("OnTheTaps.Shared.Models.BeerType", "BeerType")
                        .WithMany("BeerFamilies")
                        .HasForeignKey("BeerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeerType");
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.BeerStyle", b =>
                {
                    b.HasOne("OnTheTaps.Shared.Models.BeerFamily", "Family")
                        .WithMany("BeerStyles")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnTheTaps.Shared.Models.BeerColour", "Srmhigh")
                        .WithMany("BeerStyleSrmhighs")
                        .HasForeignKey("SrmhighId")
                        .IsRequired();

                    b.HasOne("OnTheTaps.Shared.Models.BeerColour", "Srmlow")
                        .WithMany("BeerStyleSrmlows")
                        .HasForeignKey("SrmlowId")
                        .IsRequired();

                    b.HasOne("OnTheTaps.Shared.Models.BeerType", "Type")
                        .WithMany("BeerStyles")
                        .HasForeignKey("TypeId")
                        .IsRequired();

                    b.HasOne("OnTheTaps.Shared.Models.BeerYeast", "Yeast")
                        .WithMany("BeerStyles")
                        .HasForeignKey("YeastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Srmhigh");

                    b.Navigation("Srmlow");

                    b.Navigation("Type");

                    b.Navigation("Yeast");
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.Checkin", b =>
                {
                    b.HasOne("OnTheTaps.Shared.Models.Beer", "BidNavigation")
                        .WithMany("Checkins")
                        .HasForeignKey("Bid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnTheTaps.Shared.Models.Establishment", "Establishment")
                        .WithMany("Checkins")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BidNavigation");

                    b.Navigation("Establishment");
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.Establishment", b =>
                {
                    b.HasOne("OnTheTaps.Shared.Models.Location", "Location")
                        .WithMany("Establishments")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.Beer", b =>
                {
                    b.Navigation("Checkins");
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.BeerColour", b =>
                {
                    b.Navigation("BeerStyleSrmhighs");

                    b.Navigation("BeerStyleSrmlows");
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.BeerFamily", b =>
                {
                    b.Navigation("BeerStyles");
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.BeerType", b =>
                {
                    b.Navigation("BeerFamilies");

                    b.Navigation("BeerStyles");
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.BeerYeast", b =>
                {
                    b.Navigation("BeerStyles");
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.Brewer", b =>
                {
                    b.Navigation("Beers");
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.Establishment", b =>
                {
                    b.Navigation("Checkins");
                });

            modelBuilder.Entity("OnTheTaps.Shared.Models.Location", b =>
                {
                    b.Navigation("Establishments");
                });
#pragma warning restore 612, 618
        }
    }
}
