// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace OnTheTaps.Shared.Models;

public partial class OnTheTapsContext : DbContext
{
    public OnTheTapsContext()
    {
    }

    public OnTheTapsContext(DbContextOptions<OnTheTapsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Tap> Taps { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=bigbeerdata.database.windows.net;Initial Catalog=BigBeerData.Core;Persist Security Info=True;User ID=markr;Password=worona316###");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}