// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OnTheTaps.Shared.Models;

[Table("Taps", Schema = "OTT")]
public partial class Tap
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    public int TapNo { get; set; }

    [Required]
    [StringLength(50)]
    public string BeerName { get; set; }

    [StringLength(50)]
    public string Brewery { get; set; }

    public string Description { get; set; }

    [Column(TypeName = "money")]
    public decimal? Schooner { get; set; }

    [Column(TypeName = "money")]
    public decimal? Squealer { get; set; }

    [Column(TypeName = "money")]
    public decimal? Growler { get; set; }

    [StringLength(50)]
    public string BeerType { get; set; }

    [Column(TypeName = "decimal(16, 2)")]
    public decimal? Percentage { get; set; }

    [StringLength(200)]
    public string ImageUrl { get; set; }

   [Column(TypeName = "bit")]
   public bool Empty { get; set; }
}